name: auth

services:
  postgres:
    container_name: nest-auth
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-auth
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
